### PR TITLE
Wrap the install panel to display entire output

### PR DESCRIPTION
**Pull request by weihanglo**
Related issue harvester/harvester#800.

image

### CODE REVIEW

**Comment by bk201** [comment]
Could you update the PR description like https://github.com/harvester/harvester-installer/pull/79 ?
The current description will make Github automatically resolve the corresponding issue after the PR is merged, we typically need QA to verify a fix before closing an issue.

**Comment by weihanglo** [comment]
Updated as you described. Thanks.

**Comment by guangbochen** [comment]
`Unverified commit`, please refer to the [git doc](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits) to fix it, thanks.

**Comment by weihanglo** [comment]
Just signed the commit. 👍🏾

**Review by gitlawr — APPROVED** [review]
LGTM

**Pull request merged**
