### PR TITLE
bump rancher-monitoring chart to 102.0.0+up40.1.2

### PR DESCRIPTION
**Pull request by w13915984028**
bump monitoring to 102.0.0+up40.1.2
    
      patch nginx-config file with values from 102.0.1+up40.1.2
    
      fix the tar time checking warning

      fetch rancher/shell v0.1.18, both rancher-monitoring-crd and rancher-monitoring are using it

    Signed-off-by: Jian Wang <w13915984028@gmail.com>

**Problem:**

The embedded `rancher-monitoring` in Harvester is out of dated.

**Solution:**

bump rancher-monitoring chart to` 102.0.0+up40.1.2

**Related Issue:**
https://github.com/harvester/harvester/issues/3780

**Test plan:**

<del>
note: there is an UI issue to solve, DO NOT MERGE before it is solved.  
( https://github.com/harvester/harvester/issues/3780#issuecomment-1550889891 )

cc @DaiYuzeng  @WuJun2016  @guangbochen 

update at 20230522:

In https://charts.rancher.io/index.yaml, there is `assets/rancher-monitoring/rancher-monitoring-102.0.0+up40.1.2.tgz`, but no `102.0.1+up40.1.2` , which is not formally released yet

And, in `102.0.0+up40.1.2`, there is such a bug, that is fixed in `102.0.1+up40.1.2`

https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-monitoring/102.0.1%2Bup40.1.2/charts/grafana/templates/nginx-config.yaml
```
          {{- if eq .Values.global.cattle.clusterId "local" -}}
          sub_filter '"appSubUrl":""' '"appSubUrl":"/api/v1/namespaces/{{ template "grafana.namespace" . }}/services/http:{{ template "grafana.fullname" . }}:{{ .Values.service.port }}/proxy"';
          {{- else -}}
          sub_filter '"appSubUrl":""' '"appSubUrl":"/k8s/clusters/{{ .Values.global.cattle.clusterId }}/api/v1/namespaces/{{ template "grafana.namespace" . }}/services/http:{{ template "grafana.fullname" . }}:{{ .Values.service.port }}/proxy"';
          {{- end -}}
```          
</del>

upgrade test: refer https://github.com/harvester/harvester/pull/3380

update at 20230522:

the `nginx-config` is patched, and now `rancher-monitoring` works with embedded mode in Harvester.

Test plan:
1. install new harvester with this PR
2. enable `rancher-monitoring` addon from Harvester UI
3. wait a few minutes, check cluster metrics, vm metrics on dashboard are avialable, and can click `grafana` to open embedded grafana page

### CODE REVIEW

**Review by guangbochen — COMMENTED** [review]
please help to check to disable PSP in the monitoring charts; otherwise after we bump the RKE2 to [v1.25](https://github.com/harvester/harvester-installer/pull/491) it will contain the follow issue:
```
 mcc-rancher-monitoring-crd                    0/1                       ErrApplied(1) [Cluster fleet-local/local: unable to build kubernetes objects from release manifest: resource mapping not found for name: "rancher-monitoring-crd-manager" namespace: "cattle-monitoring-system" from "": no matches for kind "PodSecurityPolicy" in v…
```

**Comment by w13915984028** [comment]
> please help to check to disable PSP in the monitoring charts; otherwise after we bump the RKE2 to [v1.25](https://github.com/harvester/harvester-installer/pull/491) it will contain the follow issue:
> 
> ```
>  mcc-rancher-monitoring-crd                    0/1                       ErrApplied(1) [Cluster fleet-local/local: unable to build kubernetes objects from release manifest: resource mapping not found for name: "rancher-monitoring-crd-manager" namespace: "cattle-monitoring-system" from "": no matches for kind "PodSecurityPolicy" in v…
> ```

@guangbochen the psp is disabled by default in `rancher-monitoring-crd`, let me check why there is such an error.

https://github.com/rancher/charts/blob/69decabd4eb77c77d008d3a33c6c19d2da73ef5d/charts/rancher-monitoring-crd/102.0.0%2Bup40.1.2/values.yaml#L8

```
# Default values for rancher-monitoring-crd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  cattle:
    psp:
      enabled: false
    systemDefaultRegistry: ""
```

**Comment by w13915984028** [comment]
> that's great, I think we are aiming to bump the monitoring chart to the latest version of [102.0.1+up40.1.2](https://github.com/rancher/charts/tree/dev-v2.7/charts/rancher-monitoring/102.0.1%2Bup40.1.2), and currently only pending on the release from the Rancher side. cc @bk201

Before rancher release a new one, we can use this PR to validate ealier. I compared `102.0.1+up40.1.2` and `102.0.0+up40.1.2`, other changes are not affecting us. We only need the broken `nginx-config`.

**Comment by w13915984028** [comment]
upgrade rancher-monitoring to 102.0.0+up40.1.2:

https://github.com/harvester/harvester/pull/3380#issuecomment-1568966634

**Review by guangbochen — APPROVED** [review]
LGTM and verified that on the new cluster, dashboards are all showing correctly, thanks.
image

**Comment by bk201** [comment]
See ImagePullBackOff on this pod in an air-gapped env:
- `rancher-monitoring-crd-create-f9sch`
  - `rancher/shell:v0.1.18`

**Comment by w13915984028** [comment]
> See ImagePullBackOff on this pod in an air-gapped env:
> 
> * `rancher-monitoring-crd-create-f9sch`
>   
>   * `rancher/shell:v0.1.18`

Ops, it was updated in https://github.com/harvester/harvester-installer/commit/74675d68c6a9d29c22c8967b97a1fe4571f6fe66 and later,

image

monitoring in 100.1 and 102. are using the same shell version

let me update the shell version

**Comment by w13915984028** [comment]
added `rancher/shell:v0.1.18` back, both `rancher-monitoring-crd` and `rancher-monitoring` are using this version, even though we may change it in `values.yaml` to `v0.1.19`, but now I do not have time to check the difference between v0.1.18 and v0.1.19, just stick to the version defined by chart.  @bk201 

make log:
```
docker image pull --quiet docker.io/rancher/shell:v0.1.8
docker.io/rancher/shell:v0.1.8
docker image pull --quiet docker.io/rancher/shell:v0.1.18
docker.io/rancher/shell:v0.1.18
docker image pull --quiet docker.io/rancher/shell:v0.1.19
docker.io/rancher/shell:v0.1.19
```

**Review by bk201 — APPROVED** [review]
lgtm

**Comment by guangbochen** [comment]
@mergify backport v1.2

**Pull request merged**
