### PR TITLE
Fix grafana in all scenarios

### PR DESCRIPTION
**Pull request by w13915984028**
**Problem:**

This is a manual backport of https://github.com/harvester/harvester-installer/pull/665, refer it.

**Solution:**

Add processing for all cases.

**Related Issue:**
https://github.com/harvester/harvester/issues/5236

**Test plan:**

Refer: https://github.com/harvester/harvester-installer/pull/665

### CODE REVIEW

**Comment by brandboat** [comment]
gentle ping @w13915984028 , I've tried applied this pr and build with havester v1.2 branch with latest commit https://github.com/harvester/harvester/commit/a822a3a42ba324f11f2b95f4d0d91486eec89233 with 3 nodes while I found the Cluster Metrics still not work. Not sure what am I missing.

image
this is the chrome console output 
Screenshot from 2024-03-11 18-58-55

And I also found that `promethus-ranch-monitoring-prometheus` is stuck in Init status, not sure if this is related
image
image

**Comment by w13915984028** [comment]
The promethues pod was not started successfully, stucking at `init`, k9s showed the volume was not mounted.

Use `kubectl get pvc -n cattle-monitoring-system` to find the volume name of pvc `prometheus-rancher-monitoring-prometheus-db-prometheus-rancher-monitoring-prometheus-0`; then `kubectl get volume -n longhorn-system pvc-name -oyaml` to get the detailed LH information.

**Comment by brandboat** [comment]
> The promethues pod was not started successfully, stucking at init, k9s showed the volume was not mounted.
> 
> Use kubectl get pvc -n cattle-monitoring-system to find the volume name of pvc prometheus-rancher-monitoring-prometheus-db-prometheus-rancher-monitoring-prometheus-0; then kubectl get volume -n longhorn-system pvc-name -oyaml to get the detailed LH information.

Huge thanks ! I discovered the volume wass detached due to insufficient disk space.

I've also confirmed that this pr is good to go, the metrics are now visible and Grafana login page no longer 404.
Screenshot from 2024-03-11 19-56-17

Screenshot from 2024-03-11 19-53-51

**Review by brandboat — APPROVED** [review]
LGTM, many thanks

**Review by bk201 — APPROVED** [review]

**Pull request merged**
