### PR TITLE
Fix build missed charts

### PR DESCRIPTION
**Pull request by w13915984028**
**Problem:**

Some charts are missed.

**Solution:**

Add then back

**Related Issue:**
https://github.com/harvester/harvester/issues/5337

**Test plan:**

build log:
```
...
Successfully packaged chart and saved it to: /go/src/github.com/harvester/harvester-installer/package/harvester-repo/charts/rancher-logging-103.0.0+up3.17.10.tgz
finish patch ranch-logging chart
pull harvester-vm-import-controller: 0.1.7
pull harvester-pcidevices-controller: 0.3.2
pull harvester-seeder: 0.1.1
...
```

### CODE REVIEW

**Comment by bk201** [comment]
need to fix the image list too: https://github.com/harvester/harvester-installer/blob/71bf39b23f13ee0e22c562fd754257800d8ea1d6/scripts/build-bundle#L185

**Comment by w13915984028** [comment]
@bk201 co-author with you

**Review by bk201 — APPROVED** [review]

**Review by ibrokethecloud — APPROVED** [review]
lgtm. thanks.

**Comment by bk201** [comment]
@mergifyio backport v1.3

**Pull request merged**
