### PR TITLE
os2: bump os2 version

### PR DESCRIPTION
**Pull request by tjjh89017**
Signed-off-by: Date Huang <date.huang@suse.com>

### CODE REVIEW

**Comment by bk201** [comment]
@tjjh89017 Looks like needing a rebase.

**Comment by tjjh89017** [comment]
rebase is done.

**Review by bk201 — APPROVED** [review]
LGTM

**Review by Vicente-Cheng — APPROVED** [review]
LGTM

**Review by FrankYang0529 — APPROVED** [review]
I can install a management node with an agent node. Thanks. LGTM.

**Pull request merged**
