### PR TITLE
Disable avahi daemon

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
**Problem:**
We need to disable avahi-daemon for the security scan.

**Solution:**
Disable avahi-daemon by default

**Related Issue:**
https://github.com/harvester/harvester/issues/3573

**Test plan:**
Check the avahi-daemon should not be enabled

### CODE REVIEW

**Review by masteryyh — APPROVED** [review]
LGTM, tested with ISO installation and using command below
```
rancher@harv:~> sudo systemctl status avahi-daemon.service
○ avahi-daemon.service - Avahi mDNS/DNS-SD Stack
     Loaded: loaded (/usr/lib/systemd/system/avahi-daemon.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
TriggeredBy: ○ avahi-daemon.socket
```

**Review by guangbochen — APPROVED** [review]
LGTM, and thanks for adding the test.

**Review by bk201 — APPROVED** [review]

**Review by starbops — APPROVED** [review]
LGTM, thanks!

**Comment by bk201** [comment]
@mergifyio backport v1.1

**Pull request merged**
