### PR TITLE
Various changes for cOS-toolkit upgrade in HarvesterOS

### PR DESCRIPTION
**Pull request by bk201**
**Depends on https://github.com/harvester/os2/pull/7 and need to test with https://github.com/harvester/os2/pull/7**

- Remove customization that is moved to HarvesterOS side.
- Adjust bind mount paths.
- Add Harvester version to Grub menu item.
  
(For formal release, the version will be used)
Screen Shot 2021-08-31 at 12 11 23 AM

### CODE REVIEW

**Review by guangbochen — APPROVED** [review]
LGTM, and can be merged after the https://github.com/harvester/os2/pull/7

**Review by guangbochen — APPROVED** [review]
LGTM, and can be merged after the https://github.com/harvester/os2/pull/7

**Review by guangbochen — APPROVED** [review]
LGTM, and can be merged after the https://github.com/harvester/os2/pull/7

**Review by gitlawr — APPROVED** [review]
LGTM

**Pull request merged**
