### PR TITLE
build: use newer elemental to build iso

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
**Problem:**
We want to bump elemental to the newer version and drop luet.

**Solution:**
update the build flow to match the new elemental binary

**Related Issue:**

**Test plan:**
1. Make sure the installation work as usual
2. Make sure the cluster operation as susal

### CODE REVIEW

**Comment by bk201** [comment]
Seems to fail with a UEFI VM:
Screenshot 2023-11-30 at 10 55 26 AM

Screenshot 2023-11-30 at 10 54 33 AM

**Review by bk201 — APPROVED** [review]
LGTM, thanks!

**Review by tserong — APPROVED** [review]
LGTM

**Review by jeff-radick-suse — APPROVED** [review]
LGTM

**Comment by Vicente-Cheng** [comment]
@mergifyio backport v1.2

**Pull request merged**
