### PR TITLE
Bump Rancher to v2.6-head and RKE2 to v1.22.7+rke2r1

### PR DESCRIPTION
**Pull request by bk201**
Deps:

- To bootstrap the first node, rancherd needs a fix: https://github.com/harvester/os2/pull/33
- To promote nodes with new Rancher: https://github.com/harvester/harvester/pull/1921

For reviewers to test this PR:

- Build the OS https://github.com/harvester/os2/pull/33
    - `scripts/build` to build a local one
    - Then change the tag in `harvester-installer/scripts/package-harvester-os` to something like `BASE_OS_IMAGE=“rancher/harvester-os:20220307-50915d4-dirty”`
    - Remove `--pull` on line 33
- Edit harvester-installer/Dockerfile.dapper
    - Map the harvester project temporarily (**remember to remove it later**), eg.
    ````
    ENV DAPPER_RUN_ARGS "-v /run/containerd/containerd.sock:/run/containerd/containerd.sock -v harvester-installer-go:/root/go -v harvester-installer-cache:/root/.cache -v /home/kiefer/codes/harvester/harvester:/go/src/github.com/harvester/harvester"
    ````
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>

### CODE REVIEW

**Comment by bk201** [comment]
https://github.com/rancher/rancher/issues/36480

**Comment by bk201** [comment]
@guangbochen The RKE2 version bump is blocked by [this rancherd issue](https://github.com/rancher/rancherd/issues/22). I'll add my workaround first.

**Review by guangbochen — APPROVED** [review]
LGTM and verified it works with the local build, probably need to re-run the CI after the dependency PRs are merged, thanks.
image

**Review by weihanglo — APPROVED** [review]
Built and run locally. LGTM

image

**Comment by bk201** [comment]
The Vagrant test runs on all dependencies merged.

**Review by johnliu55tw — APPROVED** [review]
LGTM

**Pull request merged**
