### PR TITLE
baseos: upgrade baseos

### PR DESCRIPTION
**Pull request by tjjh89017**
Upgrade from tiff package

Signed-off-by: Date Huang <date.huang@suse.com>

### CODE REVIEW

**Review by bk201 — APPROVED** [review]
LGTM

**Review by Vicente-Cheng — APPROVED** [review]
tested with upgrading.
VMs and basic operations work well.

And just a personal opinion, could you please make the commit messages more detailed?
like, what package or purpose for this baseos upgrade.

other LGTM!

**Comment by bk201** [comment]
>And just a personal opinion, could you please make the commit messages more detailed?

@tjjh89017 Please add updated packages to the PR. Thanks.

**Comment by tjjh89017** [comment]
update PR
Upgrade tiff, libtiff to 4.0.9-150000.45.16.1

**Pull request merged**
