### PR TITLE
Bump Rancher to v2.6.3-rc4 and RKE2 to v1.21.7+rke2r1

### PR DESCRIPTION
**Pull request by bk201**
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>

### CODE REVIEW

**Comment by guangbochen** [comment]
@bk201 can we also bump the RKE2 version to `v1.21.7+rke2r1` thanks.

**Comment by bk201** [comment]
@guangbochen https://github.com/rancher/rke2/issues/2229 Need to add images manually.

**Review by guangbochen — APPROVED** [review]
LGTM

**Review by johnliu55tw — APPROVED** [review]
LGTM

**Pull request merged**
