### PR TITLE
Bump baseOS to 20220705

### PR DESCRIPTION
**Pull request by tjjh89017**
Signed-off-by: Date Huang <date.huang@suse.com>

### CODE REVIEW

**Comment by bk201** [comment]
@guangbochen @Vicente-Cheng This PR should switch the based OS to SLE Micro. Please help test it if possible. Thanks!

**Review by guangbochen — COMMENTED** [review]
seems we need change the submission branch to v1.0 and update the script https://github.com/harvester/harvester-installer/blob/v1.0/scripts/build-bundle#L30 to clone Harvester v1.0 branch as well.

**Review by guangbochen — APPROVED** [review]
LGTM, the ISO build works and was able to install a new cluster successfully, the latest OS is now based on `SLE Micro 5.2`, the upgrade part also works but only runs with a simple cluster so additional cases can be verified separately, thanks.
```
NAME="SLE Micro"
VERSION="5.2"
VERSION_ID="5.2"
PRETTY_NAME="Harvester master"
ID="sle-micro-rancher"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.2"
VARIANT="Harvester"
VARIANT_ID="Harvester-20220705"
GRUB_ENTRY_NAME="Harvester master"
```
image

**Review by Vicente-Cheng — APPROVED** [review]
I build ISO with harvester master. ISO build and install successfully.
Then I create a simple cluster (with 3 VMs) and do some testing like uploading image, creating volume, creating VM, and migrating VM. It all works normally. I thought the new base OS worked well on basic cases. Thanks!

**Review by bk201 — APPROVED** [review]
LGTM!

**Pull request merged**
