### PR TITLE
feature 1787 bump monitoring chart version

### PR DESCRIPTION
**Pull request by w13915984028**
issue: https://github.com/harvester/harvester/issues/1787

verification:
with the local newly built ISO, install a new Harvester,
the rancher-monitoring chart is bumped to `100.1.0+up19.0.3`
"chart": "rancher-monitoring-100.1.0_up19.0.3"

```
harv1201:~ # kubectl get deployments rancher-monitoring-operator -n cattle-monitoring-system -o JSON
{
 ...
         "labels": {
            "app": "rancher-monitoring-operator",
            "app.kubernetes.io/instance": "rancher-monitoring",
            "app.kubernetes.io/managed-by": "Helm",
            "app.kubernetes.io/part-of": "rancher-monitoring",
            "app.kubernetes.io/version": "100.1.0_up19.0.3",
            "chart": "rancher-monitoring-100.1.0_up19.0.3",
            "heritage": "Helm",
            "objectset.rio.cattle.io/hash": "a8c87f2d01731fdad3b988f675a7c8a7da10d382",
            "release": "rancher-monitoring"
        },
...
```

### CODE REVIEW

**Review by johnliu55tw — APPROVED** [review]
LGTM

**Comment by guangbochen** [comment]
@w13915984028 will need to bump the air-gap images of the monitoring chart, please refer to https://github.com/harvester/harvester-installer/blob/master/scripts/bump-rancher and u can run `$ bash ./scripts/bump-rancher v2.6.3` to verify it.

Also need to verify those Grafana charts are working as expected, thanks.

**Comment by w13915984028** [comment]
@guangbochen the running result is as such, is validating the new ISO.
image

**Comment by w13915984028** [comment]
commit b4fdc5537ae:
Local verification:

0. Harvester cluster, newly installation: PASS
image


1. PODS: PASS
image

2. Grafana: PASS
image

3. Version check: PASS
```
rancher/rancher:v2.6.3
rancher/mirrored-prometheus-prometheus:v2.28.1
rancher/mirrored-prometheus-operator-prometheus-config-reloader:v0.50.0
```

```
harv1401:~ # kubectl get pod rancher-744568bdf6-5xdj2 -n cattle-system -o JSON
{

                "image": "rancher/rancher:v2.6.3",
                "imagePullPolicy": "IfNotPresent",


harv1401:~ # kubectl get pod prometheus-rancher-monitoring-prometheus-0 -n cattle-monitoring-system -o JSON | grep image -3
                    "--web.route-prefix=/",
                    "--web.config.file=/etc/prometheus/web_config/web-config.yaml"
                ],
                "image": "rancher/mirrored-prometheus-prometheus:v2.28.1",
                "imagePullPolicy": "IfNotPresent",
                "name": "prometheus",
                "ports": [
                    {
--
                        "value": "0"
                    }
                ],
                "image": "rancher/mirrored-prometheus-operator-prometheus-config-reloader:v0.50.0",
                "imagePullPolicy": "IfNotPresent",
                "name": "config-reloader",
                "ports": [
                    {
--

```

**Comment by w13915984028** [comment]
> @w13915984028 will need to bump the air-gap images of the monitoring chart, please refer to https://github.com/harvester/harvester-installer/blob/master/scripts/bump-rancher and u can run `$ bash ./scripts/bump-rancher v2.6.3` to verify it.
> 
> Also need to verify those Grafana charts are working as expected, thanks.

@guangbochen  Please take a look of the latest commit, thanks.

**Review by guangbochen — APPROVED** [review]
LGTM, @bk201 do u prefer to keep the Rancher version as `v2.6.3-harvester1` or it would be fine to bump to the official `v2.6.3`?

**Comment by bk201** [comment]
Bumping to 2.6.3 has the benefit to test Rancher upgrade when testing upgrading 1.0.0 to master builds

**Comment by guangbochen** [comment]
Then I will merge this PR, thanks.

**Review by bk201 — CHANGES_REQUESTED** [review]
I got `ImagePullBackOff` status of the following image in an air-gapped env:

```
rancher/mirrored-prometheus-adapter-prometheus-adapter:v0.9.0
```

Need to bump the tag as well.

**Comment by w13915984028** [comment]
> I got `ImagePullBackOff` status of the following image in an air-gapped env:
> 
> ```
> rancher/mirrored-prometheus-adapter-prometheus-adapter:v0.9.0
> ```
> 
> Need to bump the tag as well.

After updating in `scripts/images/allow.yaml`, the `prometheus-adapter` is using` rancher/mirrored-prometheus-adapter-prometheus-adapter:v0.9.0` now.

**Comment by w13915984028** [comment]
verified `commit 9fa084fe7da2` in local built ISO, `rancher/mirrored-prometheus-adapter-prometheus-adapter:v0.9.0` is updated.


```

harv1701:~ # kubectl get pods -A
NAMESPACE                   NAME                                                     READY   STATUS      RESTARTS   AGE
cattle-fleet-local-system   fleet-agent-78f694664b-c58zr                             1/1     Running     0          45m
cattle-fleet-system         fleet-controller-6666887949-bj7ll                        1/1     Running     0          46m
cattle-fleet-system         gitjob-7b97c9c7fd-9kpsh                                  1/1     Running     0          46m
cattle-monitoring-system    prometheus-rancher-monitoring-prometheus-0               3/3     Running     0          43m
cattle-monitoring-system    rancher-monitoring-grafana-d9c56d79b-kbbhc               3/3     Running     0          43m
cattle-monitoring-system    rancher-monitoring-kube-state-metrics-5bc8bb48bd-ln42q   1/1     Running     0          43m
cattle-monitoring-system    rancher-monitoring-operator-559767d69b-7h6vk             1/1     Running     0          43m
cattle-monitoring-system    rancher-monitoring-prometheus-adapter-8846d4757-72sk2    1/1     Running     0          43m
cattle-monitoring-system    rancher-monitoring-prometheus-node-exporter-f44x8        1/1     Running     0          43m
cattle-system               harvester-cluster-repo-56b5f7b585-pz7wc                  1/1     Running     0          45m

```

```
harv1701:~ #  kubectl get deployment -n cattle-monitoring-system rancher-monitoring-prometheus-adapter -o JSON | grep image
                        "image": "rancher/mirrored-prometheus-adapter-prometheus-adapter:v0.9.0",
                        "imagePullPolicy": "IfNotPresent",
harv1701:~ # kubectl get pods -n cattle-monitoring-system rancher-monitoring-prometheus-adapter-8846d4757-72sk2 -o JSON | grep image
                "image": "rancher/mirrored-prometheus-adapter-prometheus-adapter:v0.9.0",
                "imagePullPolicy": "IfNotPresent",
                "image": "docker.io/rancher/mirrored-prometheus-adapter-prometheus-adapter:v0.9.0",
                "imageID": "sha256:e45f535a68cc67ca35949e71c26ec1517f2a8fb4671cb27985f7f3809932333b",
harv1701:~ #

```

**Review by bk201 — APPROVED** [review]
LGTM, thanks for fixing the image.

**Pull request merged**
