### PR TITLE
Bump golang to v1.21

### PR DESCRIPTION
**Pull request by votdev**
**Problem:**
Go v1.20 is EOL on 06 Feb 2024.

**Solution:**
Bump golang to v1.21.

**Related Issue:**
https://github.com/harvester/harvester/issues/5310

### CODE REVIEW

**Review by tserong — APPROVED** [review]
LGTM. OOC, why the change from `run.skip-files` and `.skip-dirs` to `issues.exclude-files` and `.exclude-dirs`? I've not looked at golangci config before, so just wondering why one form would be preferred over the other.

**Comment by votdev** [comment]
> LGTM. OOC, why the change from `run.skip-files` and `.skip-dirs` to `issues.exclude-files` and `.exclude-dirs`? I've not looked at golangci config before, so just wondering why one form would be preferred over the other.

`run.skip-files` and `run.skip-dirs` are deprecated. Both the linter and my IDE reported errors here.

> ⚠️ Replace run.skip-xxx options by issues.exclude-xxx options
See https://golangci-lint.run/product/changelog/#v1570

**Comment by tserong** [comment]
Aha! Thanks, I didn't find that when looking at the docs earlier today. I still have a browser tab open which mentions `run.skip-files`: 

image

...but I've just now reloaded that page and it's changed to now show `issues.exclude-files` (and `..dirs`) at https://golangci-lint.run/usage/configuration/#issues-configuration.

It would seem I was simply extremely unlucky with my timing when reviewing this ;-)

**Review by bk201 — APPROVED** [review]
LGTM, thanks for the effort!

**Review by FrankYang0529 — APPROVED** [review]
LGTM. I can provision a cluster with PR https://github.com/harvester/harvester/pull/5454

**Review by Vicente-Cheng — APPROVED** [review]
lgtm, thanks for it!

**Comment by FrankYang0529** [comment]
@Mergify backport v1.3

**Comment by FrankYang0529** [comment]
@mergify backport v1.2

**Pull request merged**
