### PR TITLE
Add compatibility for password hashing algorithms rather than only SHA-512

### PR DESCRIPTION
**Pull request by masteryyh**
**Related issue:**
[#3051](https://github.com/harvester/harvester/issues/3051)

**Test steps:**
1. Prepare an iPXE installation environment, set the password using `openssl passwd -1` for MD5 based password;
2. Install a Harvester instance using iPXE;
3. After boot up, try to use the password set in `config.yaml` to get into the console.

### CODE REVIEW

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by starbops — APPROVED** [review]
Tested on fresh iPXE installs. LGTM, thanks!

**Review by bk201 — APPROVED** [review]
LGTM!

**Comment by bk201** [comment]
@mergifyio backport v1.1

**Pull request merged**
