### PR TITLE
fix grafana dashboard 404 issue

### PR DESCRIPTION
**Pull request by w13915984028**
fix grafana dashboard 404 issue
    
    Signed-off-by: Jian Wang <w13915984028@gmail.com>

**Problem:**

The `grafana` dashboard does not show correctly in local mode and rancher managed multi-cluster mode

**Solution:**

Config grafana nginx to generate `appSubUrl` dynamically.

**Related Issue:**
https://github.com/harvester/harvester/issues/4087

The previous issue https://github.com/harvester/harvester/issues/3780 and PR https://github.com/harvester/harvester-installer/pull/492.  Can work for local mode, but not for multi-cluster mode.

**Test plan:**

1. install Harvester
2. enable `rancher-monitoring` addon
3. view cluster metrics, vm metrics from Harvester dashboard
4. click `grafana` to open indepedent window
5. import this Harvester into Rancher
6. repeat 3 in Rancher
7. repeat 4 in Rancher
all should work

### CODE REVIEW

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by starbops — APPROVED** [review]
Tested and the Grafana dashboard showed correctly. LGTM, thanks!

**Review by bk201 — APPROVED** [review]
LGTM, thanks!

**Comment by bk201** [comment]
@mergifyio backport v1.2

**Pull request merged**
