### PR TITLE
feat: bump rancher to v2.6.9-rc3

### PR DESCRIPTION
**Pull request by FrankYang0529**
Related issue:
- https://github.com/harvester/harvester/issues/2847
- https://github.com/harvester/harvester/issues/2785

### CODE REVIEW

**Review by bk201 — APPROVED** [review]
lgtm. Test with https://github.com/harvester/harvester-installer/pull/347:
- new cluster.
- upgrade from v1.0.3.

**Comment by bk201** [comment]
**Update**: 
- When testing the PR with #347, I found it takes a long time for RKE2 to upgrade. See these messages in rancher-system-agent.
```
Sep 28 08:11:36 node2 rancher-system-agent[8114]: W0928 08:11:36.340641 8114 reflector.go:443] pkg/mod/github.com/rancher/client-go@v1.24.0-rancher1/tools/cache/reflector.go:168: watch of *v1.Secret ended with: an error on the server ("unable to decode an event from the watch stream: stream error: stream ID 5; INTERNAL_ERROR; received from peer") has prevented the request from succeeding
```
- Test upgrading two-node case, the rke2-agent on the worker node can't start.
```
Sep 28 10:05:34 node2 rke2[28576]: time="2022-09-28T10:05:34Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: https://127.0.0.1:6444/v1-rke2/serving-kubelet.crt: 503 Service Unavailable"
Sep 28 10:05:39 node2 rke2[28576]: time="2022-09-28T10:05:39Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: https://127.0.0.1:6444/v1-rke2/serving-kubelet.crt: 503 Service Unavailable"
Sep 28 10:05:44 node2 rke2[28576]: time="2022-09-28T10:05:44Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: https://127.0.0.1:6444/v1-rke2/serving-kubelet.crt: 503 Service Unavailable"
Sep 28 10:05:49 node2 rke2[28576]: time="2022-09-28T10:05:49Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: https://127.0.0.1:6444/v1-rke2/serving-kubelet.crt: 503 Service Unavailable"
Sep 28 10:05:54 node2 rke2[28576]: time="2022-09-28T10:05:54Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: https://127.0.0.1:6444/v1-rke2/serving-kubelet.crt: 503 Service Unavailable"
Sep 28 10:05:59 node2 rke2[28576]: time="2022-09-28T10:05:59Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: https://127.0.0.1:6444/v1-rke2/serving-kubelet.crt: 503 Service Unavailable"
Sep 28 10:06:04 node2 rke2[28576]: time="2022-09-28T10:06:04Z" level=info msg="Waiting to retrieve agent configuration; server is not ready: https://127.0.0.1:6444/v1-rke2/serving-kubelet.crt: 503 Service Unavailable"
```

I'll do some tests to see if this can work without bumping RKE2.

**Review by guangbochen — APPROVED** [review]
LGTM, this PR can be merged first to facilitate the test if needed, for the RKE2 we can use v1.23.x if v1.24 has any potential issues, thanks.

**Comment by FrankYang0529** [comment]
Related issues:
https://github.com/harvester/harvester/issues/2665
https://github.com/harvester/harvester/issues/2470

**Review by bk201 — APPROVED** [review]
LGTM

**Review by Vicente-Cheng — APPROVED** [review]
Test with fresh install and upgrade

some issues (already have workaround steps) happened on upgrading like
https://github.com/rancher/rancher/issues/39167

Still need some effort to investigate it.
overall LGTM.

**Pull request merged**
