### PR TITLE
os: bump OS to 20230220

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
- Serval packages update on the SLE-Mircro-for-Rancher 5.3

### CODE REVIEW

**Comment by bk201** [comment]
```
-----RPM-----

Packages found only in docker.io/rancher/harvester-os:20230209: None

Packages found only in docker.io/rancher/harvester-os:20230220: None

Version differences:
PACKAGE                            IMAGE1 (docker.io/rancher/harvester-os:20230209)        IMAGE2 (docker.io/rancher/harvester-os:20230220)
-curl                              7.79.1-150400.5.12.1, 729.5K                            7.79.1-150400.5.15.1, 729.5K
-dracut                            055+suse.323.gca0e74f0-150400.3.13.1, 1.8M              055+suse.331.g05b9ccb7-150400.3.16.1, 1.8M
-dracut-mkinitrd-deprecated        055+suse.323.gca0e74f0-150400.3.13.1, 14.6K             055+suse.331.g05b9ccb7-150400.3.16.1, 14.6K
-hwinfo                            21.83-150400.3.6.1, 3.5M                                21.84-150400.3.9.1, 3.5M
-kernel-default                    5.14.21-150400.24.41.1, 192.4M                          5.14.21-150400.24.46.1, 192.4M
-less                              590-150400.1.51, 322.2K                                 590-150400.3.3.1, 322.1K
-libcurl4                          7.79.1-150400.5.12.1, 630.7K                            7.79.1-150400.5.15.1, 630.7K
-libfreebl3                        3.79.3-150400.3.23.1, 764.7K                            3.79.4-150400.3.26.1, 764.7K
-libsoftokn3                       3.79.3-150400.3.23.1, 470.3K                            3.79.4-150400.3.26.1, 470.3K
-libtiff5                          4.0.9-150000.45.22.1, 502K                              4.0.9-150000.45.25.1, 502K
-mozilla-nss                       3.79.3-150400.3.23.1, 2M                                3.79.4-150400.3.26.1, 2M
-mozilla-nss-certs                 3.79.3-150400.3.23.1, 539.1K                            3.79.4-150400.3.26.1, 539.1K
```

**Review by bk201 — APPROVED** [review]
LGTM

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Comment by guangbochen** [comment]
@mergify backport v1.1

**Pull request merged**
