### PR TITLE
Bump K3os to v0.20.4 k3s1r0

### PR DESCRIPTION
**Pull request by gitlawr**

### CODE REVIEW

**Comment by futuretea** [comment]
Sorry, My commit caused some conflicts

**Comment by futuretea** [comment]
https://github.com/rancher/k3os/issues/686

**Comment by gitlawr** [comment]
I did a sanity check. VM creation/console access/migration, VLAN network/DHCP works

**Review by futuretea — APPROVED** [review]
LGTM

**Review by guangbochen — APPROVED** [review]
LGTM

**Pull request merged**
