### PR TITLE
common: fix random number generator

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
**Problem:**
side-effect from 1069a0c5fd825f93a25b7a87ef599c1e215ebf5c

**Solution:**
Use the correct random function

**Related Issue:**

**Test plan:**

### CODE REVIEW

**Review by bk201 — APPROVED** [review]
LGTM, thanks for the fix.

**Comment by Vicente-Cheng** [comment]
Hi all,
We use the random number generator on `harvester-installer`, `node-manager` and `node-disk-manager`.
So I prefer to wrap this into a common function and add a unit test.
This is the wrapper PR https://github.com/harvester/go-common/pull/5

Change this to draft, I will use this common function after the above PR is merged

**Comment by Vicente-Cheng** [comment]
Hi all, update to using the wrapper function from go-common.
Please help to review it again.

**Review by bk201 — APPROVED** [review]
LGTM

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Comment by guangbochen** [comment]
@mergify backport v1.2

**Pull request merged**
