### PR TITLE
Bump baseOS to 20220705

### PR DESCRIPTION
**Pull request by tjjh89017**
https://github.com/harvester/harvester/issues/2463

Signed-off-by: Date Huang <date.huang@suse.com>

### CODE REVIEW

**Review by Vicente-Cheng — APPROVED** [review]
lgtm

**Comment by bk201** [comment]
CI fails and can't provision cluster locally.
We need to backport this change as well: https://github.com/harvester/harvester-installer/pull/280

**Comment by tjjh89017** [comment]
Should I directly import that PR into this backport?

**Comment by bk201** [comment]
Since the rancherd change is included in this PR, maybe we don't need #301 ?

**Comment by tjjh89017** [comment]
But we need update `bootstrapResoucre` to `resource`, isn't it?

**Review by bk201 — APPROVED** [review]
Test new cluster provision and upgrade from v1.0.2. LGTM!

**Review by guangbochen — APPROVED** [review]
LGTM

**Review by Vicente-Cheng — APPROVED** [review]
LGTM

**Pull request merged**
