### PR TITLE
chart: bump pci-device/vm-import chart

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
related issue: https://github.com/harvester/harvester/issues/3159

### CODE REVIEW

**Review by guangbochen — APPROVED** [review]
this PR is LGTM, but we need another related PR to address the [upgrade case ](https://github.com/harvester/harvester/blob/master/package/upgrade/upgrade_manifests.sh#L619)on  [harvester/harvester](https://github.com/harvester/harvester/tree/master/package/upgrade/addons), thanks.

**Comment by Vicente-Cheng** [comment]
> this PR is LGTM, but we need another related PR to address the upgrade case on [harvester/harvester](https://github.com/harvester/harvester/tree/master/package/upgrade/addons), thanks.

Hi @guangbochen, 
Thanks for the reminder!
Open the related PR https://github.com/harvester/harvester/pull/3194, please help to review it!

**Review by masteryyh — APPROVED** [review]
LGTM, thanks.

**Review by bk201 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
