### PR TITLE
[Backport v1.0.3] console: dashboard: show node ip for identify nodes

### PR DESCRIPTION
**Pull request by tjjh89017**
please refer https://github.com/harvester/harvester/issues/2087
Test case in https://github.com/harvester/harvester/issues/2087

It will check the interface with the default route to have the primary/first IP from it.
If not, it will fall back to harvester-mgmt and get IP from it.

### Test plan

1. build harvester-installer with `make`
2. copy harvester-installer with `scp bin/harvester-installer rancher@<IP>:<PATH>
3. Switch harvester console to TTY2 or other (press CTRL+ALT+F2)
4. execute harvester-installer in current TTY `DEBUG=true HARVESTER_DASHBOARD=true TTY=/dev/tty <PATH>/harvester-installer`
5. check the screen has Node IP and IP address (refer the figure below)
Screenshot_node1_2022-06-14_10:53:17

Signed-off-by: Date Huang <date.huang@suse.com>

### CODE REVIEW

**Review by bk201 — APPROVED** [review]
LGTM!

**Review by guangbochen — APPROVED** [review]

**Comment by guangbochen** [comment]
I have updated the base branch to v1.0 and @tjjh89017 can u please help to address the conflicts, thanks.

**Comment by Vicente-Cheng** [comment]
I think that commit tree looks strange. (Some commits are already on `v1.0` branch)
@tjjh89017 Date could you rebase again on `v1.0` branch?

**Comment by tjjh89017** [comment]
> I think that commit tree looks strange. (Some commits are already on `v1.0` branch) @tjjh89017 Date could you rebase again on `v1.0` branch?

It should be correct now.
tks a lot

**Comment by tjjh89017** [comment]
We should.
Let me check it again.

**Comment by tjjh89017** [comment]
Thanks for @Vicente-Cheng.
and please help me to review again.

**Review by Vicente-Cheng — APPROVED** [review]
LGTM! thanks~

**Review by bk201 — APPROVED** [review]
LGTM

**Review by guangbochen — APPROVED** [review]

**Pull request merged**
