### PR TITLE
Revert VLAN PR 175

### PR DESCRIPTION
**Pull request by FrankYang0529**
* https://github.com/harvester/harvester-installer/pull/175
* https://github.com/harvester/harvester/issues/1390

### CODE REVIEW

**Comment by tjjh89017** [comment]
LGTM

**Review by bk201 — APPROVED** [review]
LGTM, thanks for reverting it.

**Review by johnliu55tw — APPROVED** [review]
LGTM

**Comment by guangbochen** [comment]
@FrankYang0529 can we please address the conflict, thanks

**Pull request merged**
