### PR TITLE
Bump Rancher to v2.7.5-rc5

### PR DESCRIPTION
**Pull request by bk201**
**Problem:**

We need to bump Rancher to v2.7.5-rc5

**Solution:**

Bump Rancher to v2.7.5-rc5

**Dependency**
https://github.com/rancher/rancherd/pull/31

**Related Issue:**
https://github.com/harvester/harvester/issues/3986

**Test plan:**

### CODE REVIEW

**Comment by bk201** [comment]
Commit 87cce5212ae32b7157b7e9e2bc16948bb3d91971 is added for testing, it will be removed once rancherd is bumped in the OS side.

**Comment by bk201** [comment]
RC4 is just released, I'll bump to this version.
https://github.com/rancher/rancher/releases/tag/v2.7.5-rc4

**Comment by bk201** [comment]
Note: the upgrade path needs this fix: https://github.com/harvester/harvester/pull/4050
Otherwise, per-node upgrade won't start.

**Comment by bk201** [comment]
Removed the rancherd commit because rancherd is bumped in the OS change https://github.com/harvester/os2/pull/66. Rebased on https://github.com/harvester/harvester-installer/pull/507

**Comment by bk201** [comment]
Add a commit 6b629a9ec73818c29f5ef9b5e44e8c7cca9e0673 to include the change in https://github.com/rancher/rancherd/pull/32
This speeds up the local cluster provision speed.

**Comment by bk201** [comment]
Removed rancherd commit and added [the OS bump ](https://github.com/harvester/harvester-installer/pull/510)(which contains the new rancherd).

**Review by starbops — APPROVED** [review]
LGTM, thanks!

**Comment by bk201** [comment]
@mergifyio backport v1.2

**Pull request merged**
