### PR TITLE
Bump rancher to v2.6.2

### PR DESCRIPTION
**Pull request by guangbochen**
According to the Rancher team, some rancher-related issues are already resolved in the Rancher v2.6.2.

Bump rancher to v2.6.2 to verify those dependency issues.

https://github.com/harvester/harvester/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.0.0+label%3Aarea%2Francher-related

### CODE REVIEW

**Comment by bk201** [comment]
@guangbochen It would be nice to let this in first: https://github.com/harvester/harvester-installer/pull/103
It can handle the images.

**Comment by gitlawr** [comment]
Do you think we can bump to the master version? https://github.com/rancher/rancher/issues/34908 is not available in 2.6.2

**Comment by guangbochen** [comment]
> @guangbochen It would be nice to let this in first: #103 It can handle the images.

sure, will take a review of this PR, @bk201 IIRC, we don't support fetching images from the master-head version right? so how do we specify the image when using the master-head for validation.

**Comment by bk201** [comment]
> > @guangbochen It would be nice to let this in first: #103 It can handle the images.
> 
> sure, will take a review of this PR, @bk201 IIRC, we don't support fetching images from the master-head version right? so how do we specify the image when using the master-head rancher for validation.

No, it can't handle master images because the image-list files are not published to GitHub release page.
For `master-head-xxx` releases, I need to run it in an air-gapped environment to know what are missing. :(

**Review by bk201 — APPROVED** [review]
Images look good in my air-gapped environment.

I did notice something strange in my first test. In my 4-node cluster, after bootstrapping the first node, the remaining 3 nodes take very long time to join the cluster (around ~15+ minutes)

But I didn't see this problem in another two tests.

**Comment by guangbochen** [comment]
@gitlawr @bk201 I have bumped the rancher to the latest master-head image as per https://github.com/harvester/harvester-installer/pull/159/commits/e8b40cdd100e70a598e2a87811db7ba1fc82a5b3, probably just need to do an air-gap validation, thanks.

**Comment by gitlawr** [comment]
Some pods fail to start because the following images are missing:
```
rancher/shell:v0.1.13
rancher/fleet:v0.3.8-rc1
rancher/gitjob:v0.1.22
rancher/fleet-agent:v0.3.8-rc1
rancher/system-upgrade-controller:v0.8.0
rancher/system-agent:v0.1.1-rc4-suc
```

**Comment by bk201** [comment]
@guangbochen  2a66ce5 test OK!

**Review by gitlawr — APPROVED** [review]
LGTM

**Pull request merged**
