### PR TITLE
minor change to panel flow when machine has multiple disks

### PR DESCRIPTION
**Pull request by ibrokethecloud**
**Problem:**

PR introduces a minor change to the installer to direct panel flow to password panel when node has multiple disks.

When multiple disks are present the disk choose page, after choosing the installation disk, the installer guides user to hostname panel even when install node is present.

**Solution:**

The PR changes the workflow when additional disks are present on the node.

**Related Issue:**

**Test plan:**

### CODE REVIEW

**Comment by masteryyh** [comment]
In my PR I merged installation disk and data disk, and this change seems not needed 🤔 
https://github.com/masteryyh/harvester-installer/blob/a744bb185eea6dc6cbc8b68a1ad4af3aeb7d1662/pkg/console/install_panels.go#L457

**Review by masteryyh — APPROVED** [review]
LGTM, thanks

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Review by bk201 — APPROVED** [review]
LGTM, Thanks!

**Comment by bk201** [comment]
@mergifyio backport v1.2

**Pull request merged**
