### PR TITLE
ci: move to self-hosted action runner

### PR DESCRIPTION
**Pull request by bk201**
While Jenkins instance worked in the past, I propose we move the vagrant installation CI to GitHub self-hosted action runner for
- Eliminate the need for credentials to log in to view CI logs (good for community users and us)
- Re-running a failed job updates the status back to PR. Not sure why Jenkins never works.
- Easier IaC in the source. No separate repo is needed.

Note: The drone CI part doesn't change. We still rely on it to build ISO and publish to the release server.

### CODE REVIEW

**Review by tserong — APPROVED** [review]
LGTM. Also, it seems to work, given it says "all checks passed" :-)

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, thanks for this improvement!

**Comment by bk201** [comment]
@mergifyio backport v1.2, v1.1

**Comment by bk201** [comment]
@mergifyio backport v1.2

**Comment by bk201** [comment]
@mergifyio backport v1.2

**Pull request merged**
