### PR TITLE
Disable ipv6

### PR DESCRIPTION
**Pull request by yaocw2020**
Related issue: https://github.com/harvester/harvester/issues/2962

Signed-off-by: Canwu Yao <yaocanwu@gmail.com>

### CODE REVIEW

**Comment by yaocw2020** [comment]
According to the annotations from `/etc/sysctl.config`, sysctl reads settings from multiple locations. I select to add a config file into the directory `/etc/sysctl.d`.

```
####
#
# /etc/sysctl.conf is meant for local sysctl settings
#
# sysctl reads settings from the following locations:
#   /boot/sysctl.conf-<kernelversion>
#   /lib/sysctl.d/*.conf
#   /usr/lib/sysctl.d/*.conf
#   /usr/local/lib/sysctl.d/*.conf
#   /etc/sysctl.d/*.conf
#   /run/sysctl.d/*.conf
#   /etc/sysctl.conf
#
# To disable or override a distribution provided file just place a
# file with the same name in /etc/sysctl.d/
#
# See sysctl.conf(5), sysctl.d(5) and sysctl(8) for more information
#
####
```

**Comment by abonillabeeche** [comment]
Should we also disable

```p5820:~ # systemctl status wickedd-dhcp6.service
● wickedd-dhcp6.service - wicked DHCPv6 supplicant service
     Loaded: loaded (/usr/lib/systemd/system/wickedd-dhcp6.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2022-10-18 12:17:27 UTC; 26s ago
   Main PID: 14524 (wickedd-dhcp6)
      Tasks: 1
     CGroup: /system.slice/wickedd-dhcp6.service
             └─14524 /usr/lib/wicked/bin/wickedd-dhcp6 --systemd --foreground

Oct 18 12:17:27 p5820 systemd[1]: Starting wicked DHCPv6 supplicant service...
Oct 18 12:17:27 p5820 systemd[1]: Started wicked DHCPv6 supplicant service.```

**Comment by ibrokethecloud** [comment]
The change doesnt seem to have any effect.


```
master:/etc/sysctl.d # kubectl get nodes master -o json | jq .status.addresses
[
  {
    "address": "192.168.100.140",
    "type": "InternalIP"
  },
  {
    "address": "fd7d:844d:3e17:f3ae::1fd",
    "type": "InternalIP"
  },
  {
    "address": "master",
    "type": "Hostname"
  }
]
master:/etc/sysctl.d # more ipv6.config
# disable ipv6
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```

**Comment by ibrokethecloud** [comment]
based on sysctl.d man page the file needs to be named `ipv6.conf`

**Review by ibrokethecloud — APPROVED** [review]
LGTM

**Comment by bk201** [comment]
From @ibrokethecloud , to test this with VM, we can add IPv6 to a network, example:
```
<network>
  <name>workload</name>
  <uuid>ac62e6bf-6869-41a9-a2b7-25c06c7601c9</uuid>
  <forward mode="nat">
    <nat>
      <port start="1024" end="65535"/>
    </nat>
  </forward>
  <bridge name="virbr1" stp="on" delay="0"/>
  <mac address="52:54:00:7b:ed:99"/>
  <domain name="workload"/>
  <ip address="192.168.100.1" netmask="255.255.255.0">
    <dhcp>
      <range start="192.168.100.128" end="192.168.100.254"/>
    </dhcp>
  </ip>
  <ip family="ipv6" address="fd7d:844d:3e17:f3ae::1" prefix="64">
    <dhcp>
      <range start="fd7d:844d:3e17:f3ae::100" end="fd7d:844d:3e17:f3ae::1ff"/>
    </dhcp>
  </ip>
</network>
```

**Review by tjjh89017 — APPROVED** [review]
LGTM

**Comment by ibrokethecloud** [comment]
can confirm the upgrade cycle as well:

pre upgrade v1.0.3
```
onethree:~ # ip add show harvester-mgmt
3: harvester-mgmt: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 52:54:00:7d:34:3b brd ff:ff:ff:ff:ff:ff
    inet 192.168.100.159/24 brd 192.168.100.255 scope global harvester-mgmt
       valid_lft forever preferred_lft forever
    inet6 fd7d:844d:3e17:f3ae::18b/64 scope global dynamic noprefixroute
       valid_lft 85710sec preferred_lft 85710sec
    inet6 fe80::5054:ff:fe7d:343b/64 scope link
       valid_lft forever preferred_lft forever
onethree:~ # kubectl get nodes onethree -o json | jq .status.addresses
[
  {
    "address": "192.168.100.159",
    "type": "InternalIP"
  },
  {
    "address": "onethree",
    "type": "Hostname"
  }
]
```

post upgrade, ipv6 is disabled.

```
onethree:~ # ip add show mgmt-br
4: mgmt-br: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 52:54:00:7d:34:3b brd ff:ff:ff:ff:ff:ff
    inet 192.168.100.159/24 brd 192.168.100.255 scope global mgmt-br
       valid_lft forever preferred_lft forever
    inet 192.168.100.211/32 scope global mgmt-br
       valid_lft forever preferred_lft forever

onethree:~ # kubectl get nodes onethree -o json | jq .status.addresses
[
  {
    "address": "192.168.100.159",
    "type": "InternalIP"
  },
  {
    "address": "onethree",
    "type": "Hostname"
  }
]
```

users may notice a transient error until the node is rebooted as part of the upgrade process

image

**Review by guangbochen — APPROVED** [review]

**Comment by bk201** [comment]
I can reproduce the issue by enabling slaac in my dnsmasq config:
```
dhcp-range=2001:db8:0:1::129, 2001:db8:0:1::254, slaac, 1h
```
Disabling IPv6 apparently fixes the issue.

**Review by bk201 — APPROVED** [review]

**Pull request merged**
