### PR TITLE
[DNM] Bump OS to 20211220

### PR DESCRIPTION
**Pull request by bk201**
Fix GRUB rebranding issue.

Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>

### CODE REVIEW

**Review by guangbochen — DISMISSED** [review]
LGTM

**Review by weihanglo — APPROVED** [review]
Confirmed that image is published.

- https://drone-publish.rancher.io/harvester/os2/34/1/3
- https://hub.docker.com/r/rancher/harvester-os/tags?page=1&name=20211220

**Review by johnliu55tw — APPROVED** [review]

**Comment by johnliu55tw** [comment]
My VM can't boot from the ISO built from this change. Need some further check.

**Comment by weihanglo** [comment]
Cannot boot the ISO either. See https://github.com/harvester/harvester/pull/1706#issuecomment-997696375

**Comment by bk201** [comment]
Screen Shot 2021-12-20 at 4 23 47 PM

Saw these in serial console.

**Comment by bk201** [comment]
Should be caused by the [cos-setup bump from 0.5 to 0.6](https://github.com/rancher-sandbox/cOS-toolkit/pull/976/). `yip` tool is renamed to `elemental` but we don't have it in the ISO.

**Comment by guangbochen** [comment]
let's leave this one for the `v1.0.1` milestone, thanks.

**Pull request closed without merging**
