### PR TITLE
Bump Rancher to v2.6.4-rc8

### PR DESCRIPTION
**Pull request by guangbochen**
Bump Rancher to v2.6.4-rc8

### CODE REVIEW

**Review by bk201 — APPROVED** [review]
LGTM

**Review by weihanglo — APPROVED** [review]
The flooding issue is still not fixed but other stuff is ok.
image

**Comment by bk201** [comment]
@weihanglo Is this always flooding the rancher pod in your setup?

**Comment by weihanglo** [comment]
Yep. I installed a single node cluster from ISO built from this commit. Then I uploaded the same harvester ISO from file and check the log via `kubectl -n harvester-system logs deploy/harvester`.

**Comment by guangbochen** [comment]
Should we merge and track it seperately?

**Comment by bk201** [comment]
@guangbochen Sure, Weihang mentioned he also saw this before. To correct my comments, they are messages in the harvester deployment.

**Comment by weihanglo** [comment]
@guangbochen go ahead. I believe it is an existing issue and should not block this bump.

**Comment by w13915984028** [comment]
@weihanglo Please also take a look of grafana when uploading image, as following.

The pause/resume mechanism will eliminate the caching data to around 4M,  before this merge, Harvester may cache G level data.

https://github.com/harvester/harvester/issues/1956#issuecomment-1064942807

**Comment by w13915984028** [comment]
Harvester POD memroy usage is smooth with this new bump:
@weihanglo @guangbochen @bk201 @yasker 
refer:
https://github.com/harvester/harvester/issues/1956#issuecomment-1064964676

**Comment by w13915984028** [comment]
for the error message

Commits on Feb 18, 2022
https://github.com/rancher/remotedialer/commit/31afcc1bf5a6e0e56b6ba3f05c1da703b5d1e562

Change error log to debug log
This log seems more of a debug log as it's just stating that
the buffer is being reset and there is nothing to indicate
this is not expected or normal behavior.

 [master](https://github.com/rancher/remotedialer) ([#41](https://github.com/rancher/remotedialer/pull/41)[](https://github.com/rmweir))
@[rmweir](https://github.com/rancher/remotedialer/commits?author=rmweir)
rmweir committed 21 days ago 
1 parent [266bce3](https://github.com/rancher/remotedialer/commit/266bce3580f2d2f8219fbe38fe0bb52613b55d9f) commit 31afcc1bf5a6e0e56b6ba3f05c1da703b5d1e562

**Pull request merged**
