### PR TITLE
elemental: bump elemental-cli to v0.1.0

### PR DESCRIPTION
**Pull request by tjjh89017**
We cannot use Elemental-cli InstallSpec struct to generate config.yaml. Because there are not all entry with "omitempty", it will cause generated config.yaml will have several empty entry but didn't be omitted.
Elemental-cli will treat those empty entry as user-specific value and override the default value.

Use ElementalInstallSpec to ensure that all entry will be "omitempty".

We must to use patched OS2 image to build iso
`git clone -b elemental https://github.com/tjjh89017/os2`
https://github.com/harvester/os2/pull/51

Signed-off-by: Date Huang <date.huang@suse.com>

### CODE REVIEW

**Review by starbops — APPROVED** [review]
Just one nit, the rest LGTM!

I also tested on single node installation, looks good. Thanks!

**Comment by bk201** [comment]
Please help rebase, thanks.

**Comment by tjjh89017** [comment]
rebase done.

**Comment by bk201** [comment]
I have `install.poweroff: true` in my config file, and the flag seems not to be respected.
The node reboots after the installation rather than shutdown.

**Comment by tjjh89017** [comment]
> I have `install.poweroff: true` in my config file, and the flag seems not to be respected.
> The node reboots after the installation rather than shutdown.

Could you try the harvester v1.1.1 also?
I think it should be harvester installer bug in go code part

**Comment by bk201** [comment]
The disk partition order changes as well. Can we stick to the previous one?
Old:
```
vda
vda1
vda2 COS_OEM         /oem
vda3 COS_STATE       /run/initramfs/cos-state
vda4 COS_RECOVERY
vda5 COS_PERSISTENT  /usr/local
vda6 HARV_LH_DEFAULT /var/lib/harvester/defaultdisk
```

New:
```
vda
vda1
vda2 COS_OEM         /oem
vda3 COS_RECOVERY
vda4 COS_STATE       /run/initramfs/cos-state
vda5 COS_PERSISTENT  /usr/local
vda6 HARV_LH_DEFAULT /var/lib/harvester/defaultdisk
```

**Comment by tjjh89017** [comment]
> The disk partition order changes as well. Can we stick to the previous one? Old:
> 
> ```
> vda
> vda1
> vda2 COS_OEM         /oem
> vda3 COS_STATE       /run/initramfs/cos-state
> vda4 COS_RECOVERY
> vda5 COS_PERSISTENT  /usr/local
> vda6 HARV_LH_DEFAULT /var/lib/harvester/defaultdisk
> ```
> 
> New:
> 
> ```
> vda
> vda1
> vda2 COS_OEM         /oem
> vda3 COS_RECOVERY
> vda4 COS_STATE       /run/initramfs/cos-state
> vda5 COS_PERSISTENT  /usr/local
> vda6 HARV_LH_DEFAULT /var/lib/harvester/defaultdisk
> ```

Elemental cli didn't provide partition order.
It will be elemental limit currently.

**Comment by tjjh89017** [comment]
The "install.poweroff: true" is a bug.
I will dig into it to check the problem.

**Comment by tjjh89017** [comment]
`install.poweroff: true` issue is fixed and tested.

**Comment by Vicente-Cheng** [comment]
> > The disk partition order changes as well. Can we stick to the previous one? Old:
> > ```
> > vda
> > vda1
> > vda2 COS_OEM         /oem
> > vda3 COS_STATE       /run/initramfs/cos-state
> > vda4 COS_RECOVERY
> > vda5 COS_PERSISTENT  /usr/local
> > vda6 HARV_LH_DEFAULT /var/lib/harvester/defaultdisk
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > New:
> > ```
> > vda
> > vda1
> > vda2 COS_OEM         /oem
> > vda3 COS_RECOVERY
> > vda4 COS_STATE       /run/initramfs/cos-state
> > vda5 COS_PERSISTENT  /usr/local
> > vda6 HARV_LH_DEFAULT /var/lib/harvester/defaultdisk
> > ```
> 
> Elemental cli didn't provide partition order. It will be elemental limit currently.

Could we check about the related changes on elemental-cli?
I wonder if something depending on the specific partition `number` would meet some problems.

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, test with fresh installation with #373. Thanks!

**Review by bk201 — APPROVED** [review]
LGTM, thanks!

**Comment by bk201** [comment]
Please help tag a new os2 release and bump the OS to let CI run again.

**Comment by bk201** [comment]
@Mergifyio backport v1.1

**Pull request merged**
