### PR TITLE
feat: bump go to v1.20.10

### PR DESCRIPTION
**Pull request by FrankYang0529**
**Problem:**
We used go 1.18, which is EOL in 2023/02.

**Solution:**
Bump golang to v1.20.10.

**Related Issue:**
https://github.com/harvester/security/issues/38

### CODE REVIEW

**Comment by Vicente-Cheng** [comment]
Should we change this line https://github.com/harvester/harvester-installer/blob/master/Dockerfile.dapper#L21 for `go1.20`?

**Review by bk201 — APPROVED** [review]
lgtm!

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, thanks!

**Comment by Vicente-Cheng** [comment]
@mergifyio backport v1.2

**Comment by Vicente-Cheng** [comment]
@Mergifyio backport v1.1

**Pull request merged**
