### PR TITLE
Bump Rancher 2.8.1 and RKE2 1.27.9

### PR DESCRIPTION
**Pull request by bk201**
**Related Issue:**

https://github.com/harvester/harvester/issues/5041

**Test plan:**
- Start the cluster and make sure the cluster bootstrap.
- Verify the Rancher version and RKE2 version.

### CODE REVIEW

**Review by Vicente-Cheng — COMMENTED** [review]
Verified rancher/rke2 version as below after upgrade.
```
rancher    ●    rancher/rancher:v2.8.1    true    Running    false
```

```
  nodeInfo:
    ...
    kubeProxyVersion: v1.27.9+rke2r1
    kubeletVersion: v1.27.9+rke2r1
    ...
```

I found something strange with the upgrade. The guest VM can not migrate well during upgrade.

Below are some logs, I will check again. Should not related to this PR.
```
2024-01-31T13:23:48.555760707Z stderr F {"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/rke2-guest-01-pool1-b4649f31-9g2nx","pos":"vm.go:1588","reason":"syncing migration target failed: unknown error encountered sending command SyncMigrationTarget: rpc error: code = Unavailable desc = error reading from server: EOF","timestamp":"2024-01-31T13:23:48.555655Z"}
...
2024-01-31T13:25:33.067561695Z stderr F {"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/rke2-guest-01-pool1-b4649f31-9g2nx","pos":"vm.go:1588","reason":"syncing migration target failed: unknown error encountered sending command SyncMigrationTarget: rpc error: code = Unavailable desc = error reading from server: EOF","timestamp":"2024-01-31T13:25:33.067501Z"}
...
2024-01-31T13:34:22.398539648Z stderr F {"component":"virt-handler","level":"info
","msg":"re-enqueuing VirtualMachineInstance default/rke2-guest-01-pool1-b4649f31-9g2nx","pos":"vm.go:1588","reason":"syncing migration target failed: unknown error encountered sending command SyncMigrationTarget: rpc error: code = Unavailable desc = error reading from server: EOF","timestamp":"2024-01-31T13:34:22.398483Z"}
...
2024-01-31T13:40:03.780008282Z stderr F {"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/rke2-guest-01-pool1-b4649f31-9g2nx","pos":"vm.go:1588","reason":"Can not update a VirtualMachineInstance with unresponsive command server.","timestamp":"2024-01-31T13:40:03.779846Z"}
...
2024-01-31T13:42:05.481328521Z stderr F {"component":"virt-handler","kind":"","level":"info","msg":"Performing final local cleanup for vmi with uid d8cb8184-dc73-4f2f-b9b0-c22d204d9757","name":"rke2-guest-01-pool1-b4649f31-9g2nx","namespace":"default","pos":"vm.go:2062","timestamp":"2024-01-31T13:42:05.480996Z","uid":"d8cb8184-dc73-4f2f-b9b0-c22d204d9757"}
```

**Review by ibrokethecloud — APPROVED** [review]
lgtm. thanks. 
tested out new install and upgrade path.

**Comment by bk201** [comment]
> Verified rancher/rke2 version as below after upgrade.
> 
> ```
> rancher    ●    rancher/rancher:v2.8.1    true    Running    false
> ```
> 
> ```
>   nodeInfo:
>     ...
>     kubeProxyVersion: v1.27.9+rke2r1
>     kubeletVersion: v1.27.9+rke2r1
>     ...
> ```
> 
> I found something strange with the upgrade. The guest VM can not migrate well during upgrade.
> 
> Below are some logs, I will check again. Should not related to this PR.
> 
> ```
> 2024-01-31T13:23:48.555760707Z stderr F {"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/rke2-guest-01-pool1-b4649f31-9g2nx","pos":"vm.go:1588","reason":"syncing migration target failed: unknown error encountered sending command SyncMigrationTarget: rpc error: code = Unavailable desc = error reading from server: EOF","timestamp":"2024-01-31T13:23:48.555655Z"}
> ...
> 2024-01-31T13:25:33.067561695Z stderr F {"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/rke2-guest-01-pool1-b4649f31-9g2nx","pos":"vm.go:1588","reason":"syncing migration target failed: unknown error encountered sending command SyncMigrationTarget: rpc error: code = Unavailable desc = error reading from server: EOF","timestamp":"2024-01-31T13:25:33.067501Z"}
> ...
> 2024-01-31T13:34:22.398539648Z stderr F {"component":"virt-handler","level":"info
> ","msg":"re-enqueuing VirtualMachineInstance default/rke2-guest-01-pool1-b4649f31-9g2nx","pos":"vm.go:1588","reason":"syncing migration target failed: unknown error encountered sending command SyncMigrationTarget: rpc error: code = Unavailable desc = error reading from server: EOF","timestamp":"2024-01-31T13:34:22.398483Z"}
> ...
> 2024-01-31T13:40:03.780008282Z stderr F {"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/rke2-guest-01-pool1-b4649f31-9g2nx","pos":"vm.go:1588","reason":"Can not update a VirtualMachineInstance with unresponsive command server.","timestamp":"2024-01-31T13:40:03.779846Z"}
> ...
> 2024-01-31T13:42:05.481328521Z stderr F {"component":"virt-handler","kind":"","level":"info","msg":"Performing final local cleanup for vmi with uid d8cb8184-dc73-4f2f-b9b0-c22d204d9757","name":"rke2-guest-01-pool1-b4649f31-9g2nx","namespace":"default","pos":"vm.go:2062","timestamp":"2024-01-31T13:42:05.480996Z","uid":"d8cb8184-dc73-4f2f-b9b0-c22d204d9757"}
> ```

The issue is tracked in https://github.com/harvester/harvester/issues/5076

**Review by FrankYang0529 — APPROVED** [review]
LGTM. Thank you.

**Pull request merged**
