### PR TITLE
common: always set log level to debug when we install

### PR DESCRIPTION
**Pull request by Vicente-Cheng**
**Problem:**
Try to get more logs when we use the elemental command.

**Solution:**
Add debug parameter

**Related Issue:**
https://github.com/harvester/harvester/issues/4541

**Test plan:**
make sure the installation as usual

### CODE REVIEW

**Review by masteryyh — APPROVED** [review]
LGTM, tested installation successful with a lot of logs.
BTW, why don't we add another GRUB menu entry for debug mode? It's somewhat confusing when seeing a lot of message outputs compares to earlier versions.

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Comment by Vicente-Cheng** [comment]
> LGTM, tested installation successful with a lot of logs. BTW, why don't we add another GRUB menu entry for debug mode? It's somewhat confusing when seeing a lot of message outputs compares to earlier versions.

Thanks @masteryyh for this question!
Did you mean the `rd.debug` for the grub parameter?
That will not only affect the elemental output but will append more like dracut ... etc.

For the installation, we might not set the debug flag as default because we could try again and add `rd.debug` or `--debug` for it.
But we need to add a debug flag as default for the upgrade because we could not try again easily.

If you all thought we could add a debug flag once an error happened on installation, I will close this PR.
Feel free to give some thoughts on it! Thanks!! cc @bk201, @guangbochen, @masteryyh

**Review by bk201 — APPROVED** [review]

**Comment by bk201** [comment]
@mergifyio backport v1.2

**Pull request merged**
