### PR TITLE
change order of interface startup

### PR DESCRIPTION
**Pull request by ibrokethecloud**
**Problem:**

PR changes the order of nic startup to avoid nic renaming conflicts

**Solution:**

**Related Issue:**

**Test plan:**

### CODE REVIEW

**Review by tserong — APPROVED** [review]

**Review by Vicente-Cheng — APPROVED** [review]

**Comment by ibrokethecloud** [comment]
@mergifyio backport v1.4

**Comment by ibrokethecloud** [comment]
@mergifyio backport v1.3

**Comment by w13915984028** [comment]
@ibrokethecloud @bk201 

Do we have related upgrade processing? thanks.

**Comment by w13915984028** [comment]
Confirmed in the upgraded cluster, the file also has the new content.


```
sudo -i cat /system/oem/90_network.yaml
...
  network:
    - name: Bring up interfaces
      commands:
      - |
        for i in /sys/class/net/{eth*,en*,ib*}; do
          [ -e $i ] || continue
          ip link set $(basename $i) up;
```

**Comment by bk201** [comment]
yeah it's packaged in the squashfs and should be updated after a OS upgrade.

**Pull request merged**
