### PR TITLE
feat: add VIP mac address input panel

### PR DESCRIPTION
**Pull request by ihcsim**
**Problem:**

There is a parity gap between the VIP configuration of the ISO installation and the automatic installation modes. In the automatic installation mode, user can specify the VIP MAC and static IP addresses over DHCP. This allows user to use a static IP address as the cluster's VIP. This option isn't available in the ISO installation mode.

**Solution:**

This PR updates the VIP configuration page of the installation console with a new `MAC Address` field, to allow user to specify the VIP's MAC address in DHCP mode. The installer uses this MAC address to request for the specific static IP address over DHCP. If this field is left blank, the installer falls back to the current behaviour of determining the VIP and MAC address.

On the VIP page, the subsequent input panels that will be shown are based on the method selected by the user:

image

Choosing `DHCP` reveals both the `MAC Address` and `VIP` input panels:

image

Choosing `Static` reveals only the `VIP` input panel:

image

**Related Issue:**

https://github.com/harvester/harvester/issues/6960.

**Test plan:**

## Test Case 1 - Request For Static VIP Address Using Custom MAC Address

Follow the instructions in this [gist](https://gist.github.com/ihcsim/c33b135925ad9c8a13f12e34727be559) to add custom MAC/IP address bindings to the local kvm dnsmasq.

On the VIP page, input the custom MAC address (`32:34:1a:75:7f:64`):
  * Expect the installer to receive the pre-configured static IP (`192.168.122.39`) from the DHCP server

image

Complete the rest of the installation setup to provision Harvester.
  * Expect the management node to be ready
    
Provision a worker node to join the cluster targeting the static VIP address.
  * Expect the worker to be successfully added to the cluster

## Test Case 2 - Let Installer Determine The VIP and MAC Address

On the VIP page, leave the MAC and VIP addresses blank.
  * Expect the installer to receive a new VIP from the DHCP server with a new random MAC address
   
Complete the rest of the installation setup to provision Harvester.
  * Expect the installation to complete successfully
 
Provision a worker node to join the cluster via the static VIP address.
  * Expect the worker to be successfully added to the cluster

### CODE REVIEW

**Comment by ihcsim** [comment]
@w13915984028 let me know what you think of this approach.

**Review by w13915984028 — APPROVED** [review]
LGTM, thanks @ihcsim

**Review by bk201 — APPROVED** [review]
lgtm!

**Review by mingshuoqiu — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
