### PR TITLE
package pcidevices addon

### PR DESCRIPTION
**Pull request by ibrokethecloud**
PR introduces changes to package up pcidevices-controller as an addon in the harvester-installer

### CODE REVIEW

**Comment by ibrokethecloud** [comment]
Related to: https://github.com/harvester/harvester/issues/2913

**Review by bk201 — APPROVED** [review]
Screen Shot 2022-10-12 at 5 29 50 PM
LGTM!
Right now the image tag and chart version are coded in many places (including the upgrade path) and we might forget one of them when bumping versions.
We can factor later to see if these versions can be controlled in a single file.

**Review by guangbochen — APPROVED** [review]
LGTM, thanks for the changes.

**Review by Vicente-Cheng — APPROVED** [review]
Tested with the upgrade!
The AddOn works well.

LGTM!

**Pull request merged**
