### PR TITLE
Bump Rancher to v2.7.5

### PR DESCRIPTION
**Pull request by bk201**
**Problem:**

We need to bump Rancher to 2.7.5.

**Solution:**

Bump Rancher to 2.7.5.

**Related Issue:**
https://github.com/harvester/harvester/issues/3747

**Test plan:**

### CODE REVIEW

**Review by futuretea — APPROVED** [review]
LGTM, thanks.

**Comment by bk201** [comment]
For upgrade, please test with https://github.com/harvester/harvester/pull/4149

**Review by guangbochen — APPROVED** [review]
LGTM, and prefer to have this one merged first for the other depdency PR https://github.com/harvester/harvester/pull/4149 and https://github.com/harvester/harvester/pull/4170 validations.

**Review by Vicente-Cheng — APPROVED** [review]
LGTM, tested with https://github.com/harvester/harvester/pull/4149, https://github.com/harvester/harvester/pull/4170
Upgrade from v1.1.2, and all basic operations work normally.

**Review by chrisho — APPROVED** [review]
LGTM, tested with https://github.com/harvester/harvester/pull/4149 upgrade from v1.1.2 and working normally, thanks.

**Comment by guangbochen** [comment]
@mergify backport v1.2

**Pull request merged**
