### PR TITLE
fix(install_panels): add log for NTP validation

### PR DESCRIPTION
**Pull request by FrankYang0529**
* log NTP validation error

issue: https://github.com/harvester/harvester/issues/1248

### CODE REVIEW

**Review by bk201 — APPROVED** [review]
It would be nice to display the errors to users too.

**Comment by FrankYang0529** [comment]
> It would be nice to display the errors to users too.

After testing, I think we have enough space to show error message to users. Updated it. Thank you

**Review by guangbochen — APPROVED** [review]
LGTM

**Review by gitlawr — APPROVED** [review]
LGTM

**Pull request merged**
