### PR TITLE
Bump rancher to v2.6-4-rc10

### PR DESCRIPTION
**Pull request by bk201**
Bumping rancher to address these two issues:
- https://github.com/harvester/harvester/issues/1984
- https://github.com/rancher/rancher/issues/35999

### CODE REVIEW

**Review by guangbochen — COMMENTED** [review]
We can bump to [v2.6.4-rc10](https://github.com/rancher/rancher/releases/tag/v2.6.4-rc10) if needed, thanks.

**Comment by bk201** [comment]
> We can bump to [v2.6.4-rc10](https://github.com/rancher/rancher/releases/tag/v2.6.4-rc10) if needed, thanks.

Sure, bumped.

**Review by guangbochen — APPROVED** [review]
LGTM

**Review by weihanglo — APPROVED** [review]
LGTM

**Pull request merged**
